server:
  port: 8080
okta:
  oauth2:
    issuer: https://localhost:8081/auth/oauth/token
    client-id: R2dpxQ3vPrtfgF72
    client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
spring:
  thymeleaf:
    cache: false
